import { en } from "@/lib/i18n/dictionaries/en";
import type { Dictionary } from "@/lib/i18n/types";

export const es: Dictionary = {
  ...en,
  metadata: { homeTitle: "TransferHub | Una aplicación. Todas tus transferencias.", homeDescription: "Explora comparaciones ficticias e ilustrativas de transferencias según comisiones, tipos de cambio, métodos de entrega y plazos.", marketplaceTitle: "Mercado de transferencias | TransferHub", marketplaceDescription: "Explora los corredores ficticios disponibles en el prototipo de TransferHub.", waitlistTitle: "Únete a la lista de espera | TransferHub", waitlistDescription: "Únete para recibir ocasionalmente novedades de TransferHub." },
  common: { chooseLanguage: "Elegir idioma", illustrativeUnavailable: "La información ilustrativa del proveedor no está disponible", fictionalProviders: "Proveedores y valores ficticios", sampleScenario: "Escenario de ejemplo.", actualValuesMayDiffer: "Las comisiones, tasas, disponibilidad, métodos de entrega y plazos reales pueden variar. TransferHub no inicia transferencias actualmente.", copyright: "© 2026 TransferHub.info." },
  navigation: { primary: "Navegación principal", menu: "Abrir el menú de navegación", home: "Inicio", marketplace: "Mercado", features: "Funciones", howItWorks: "Cómo funciona", about: "Acerca de", faq: "Preguntas", waitlist: "Lista de espera", joinWaitlist: "Únete a la lista", signIn: "Iniciar sesión", comingSoon: "próximamente", backHome: "Volver al inicio" },
  homepage: {
    hero: { eyebrow: "CREADO PARA FAMILIAS DE TODO EL MUNDO", titleStart: "Una aplicación.", titleEmphasis: "Todas tus transferencias.", description: "Explora cómo podrían compararse las opciones según comisiones, tipos de cambio, métodos de entrega y plazos. Todos los resultados actuales son ficticios e ilustrativos.", launchNote: "No necesitas realizar una transferencia. Sé de los primeros en conocer el lanzamiento." },
    features: { eyebrow: "TODO EN UN SOLO LUGAR", title: "Claridad antes de enviar", description: "TransferHub se está creando para que comparar opciones de transferencia sea más sencillo, rápido y fácil de entender.", items: [
      { id: "fee", title: "Comparar comisiones", description: "Consulta comisiones ilustrativas lado a lado antes de elegir una opción." },
      { id: "rate", title: "Revisar tipos de cambio", description: "Comprende cómo el tipo de cambio puede afectar lo que recibe el destinatario." },
      { id: "speed", title: "Revisar la rapidez", description: "Compara plazos estimados, desde minutos hasta varios días." },
      { id: "wallet", title: "Explorar métodos de entrega", description: "Revisa posibles opciones de depósito bancario, retiro en efectivo y billetera móvil." },
      { id: "people", title: "Guardar destinatarios", description: "Mantén sus datos organizados para facilitar la próxima experiencia." },
      { id: "track", title: "Seguir transferencias", description: "Sigue el progreso de una transferencia en una vista clara y fácil de entender." },
    ] },
    howItWorks: { eyebrow: "SIMPLE POR DISEÑO", title: "Cómo funcionará TransferHub", description: "Un camino más claro desde la decisión hasta la entrega, sin cambiar entre pestañas.", steps: [
      { id: "enter", number: "01", title: "Ingresa tu transferencia", description: "Elige el origen, el destino y el monto." }, { id: "compare", number: "02", title: "Compara tus opciones", description: "Revisa detalles ilustrativos según los factores que te importan." }, { id: "choose", number: "03", title: "Elige con confianza", description: "Selecciona tu opción preferida cuando haya conexiones autorizadas disponibles." },
    ] },
    about: { eyebrow: "PENSADO DESDE EL PRINCIPIO", titleStart: "Diseñado para la seguridad.", titleEnd: "Creado para la transparencia.", description: "TransferHub se diseña teniendo en cuenta la seguridad, la privacidad y el etiquetado transparente. Distinguiremos claramente la información ilustrativa de los datos verificados.", learnMore: "Conoce más sobre nuestro enfoque", items: [
      { id: "shield", title: "Diseño enfocado en la seguridad", description: "Se considerarán medidas de protección durante todo el desarrollo." }, { id: "eye", title: "Etiquetas de datos claras", description: "Los datos preliminares, ilustrativos y autorizados estarán claramente identificados." }, { id: "lock", title: "Privacidad en mente", description: "Buscamos recopilar únicamente lo necesario para la experiencia." }, { id: "check", title: "Sin respaldos implícitos", description: "Los listados no sugerirán asociaciones que no existan." },
    ] },
    roadmap: { eyebrow: "LO QUE ESTAMOS CREANDO", title: "El camino por delante", description: "Un recorrido deliberado hacia una comparación de transferencias más clara.", items: [
      { id: "website", number: "01", title: "Sitio y lista de espera", timing: "Ahora", status: "En vivo" }, { id: "comparison", number: "02", title: "Plataforma de comparación", timing: "Siguiente", status: "En diseño" }, { id: "providers", number: "03", title: "Integraciones autorizadas", timing: "Más adelante", status: "Planificado" }, { id: "mobile", number: "04", title: "Aplicaciones móviles", timing: "Futuro", status: "Planificado" },
    ] },
    faq: { eyebrow: "PREGUNTAS Y RESPUESTAS", title: "Preguntas frecuentes", description: "Lo que debes saber mientras TransferHub toma forma.", items: [
      { id: "what", question: "¿Qué es TransferHub?", answer: "TransferHub es una plataforma de comparación en desarrollo para revisar opciones de transferencia en un solo lugar, inicialmente centrada en Haití." }, { id: "send", question: "¿Puedo enviar dinero con TransferHub hoy?", answer: "No. La versión 0.1.0 es un prototipo interactivo y una lista de espera de desarrollo. Enviar dinero requeriría conexiones autorizadas y medidas adicionales." }, { id: "partners", question: "¿TransferHub se asocia con los proveedores mostrados?", answer: "No se afirma ninguna asociación ni integración. Todos los datos preliminares son ilustrativos hasta que existan conexiones autorizadas." }, { id: "comparison", question: "¿Cómo funcionarán las comparaciones?", answer: "La plataforma organizará comisiones, tipos de cambio, métodos y plazos para que las opciones puedan revisarse lado a lado." }, { id: "countries", question: "¿TransferHub admitirá países además de Haití?", answer: "Haití es el enfoque inicial. Podrían añadirse otros corredores cuando haya datos confiables disponibles." }, { id: "access", question: "¿Cómo puedo obtener acceso anticipado?", answer: "Únete a la lista de espera para recibir ocasionalmente novedades del producto." },
    ] },
    footer: { taglineStart: "Una aplicación. Todas tus transferencias.", taglineEnd: "Comparaciones más claras.", navigationLabel: "Navegación del pie de página", privacy: "Privacidad", terms: "Términos", security: "Seguridad", contact: "Contacto", about: "Acerca de", rights: "© 2026 TransferHub.info. Todos los derechos reservados.", disclosure: "La información mostrada es ilustrativa y no implica asociación ni respaldo." },
  },
  comparison: { ...en.comparison, findOptions: "Encuentra tus opciones", compareTransfer: "Compara una transferencia", fromCountry: "País de origen", toCountry: "País de destino", amountToSend: "Monto a enviar", amountHelp: "Ingresa entre 10 y 10.000 {currency}, con un máximo de dos decimales.", quickAmounts: "Montos rápidos en {currency}", compareOptions: "Comparar opciones", comparing: "Comparando…", swapCountries: "Intercambiar países", swapLabel: "Intercambiar países: {from} y {to}", swapTitle: "Intercambiar origen y destino", reverseUnavailable: "El corredor inverso no está disponible.", preview: "Vista previa de la comparación", youSend: "Envías", sampleBanner: "DATOS ILUSTRATIVOS DE EJEMPLO — NO SON COTIZACIONES EN VIVO", payoutMethod: "Método de entrega", allPayoutMethods: "Todos los métodos", bankDeposit: "Depósito bancario", cashPickup: "Retiro en efectivo", mobileWallet: "Billetera móvil", cashOrBank: "Efectivo o banco", sortBy: "Ordenar por", bestValue: "Mejor valor", lowestFee: "Comisión más baja", fastest: "Más rápido", highestRecipient: "Mayor monto recibido", provider: "Proveedor", fee: "Comisión", rate: "Tasa", delivery: "Entrega", payout: "Método", recipientGets: "El destinatario recibe", actions: "Acciones", viewDetails: "Ver detalles", detailsOpen: "Detalles abiertos", noFilterResults: "Ninguna opción ilustrativa coincide con este filtro.", clearFilter: "Quitar filtro", loading: "Preparando tu comparación de ejemplo…", unavailable: "Comparación ilustrativa no disponible", unavailableMessage: "Este corredor no está disponible en los datos ficticios actuales.", enterAmount: "Ingresa un monto para enviar.", invalidAmount: "Ingresa un monto válido con un máximo de dos decimales.", minimumAmount: "Ingresa al menos 10 {currency}.", maximumAmount: "Ingresa como máximo 10.000 {currency}.", notUpdated: "La comparación no se actualizó. Corrige el monto e inténtalo de nuevo.", comparingStatus: "Comparando opciones ilustrativas.", readyStatus: "Comparación lista para {amount} de {from} a {to}.", resultSingle: "Se muestra 1 opción ilustrativa.", resultPlural: "Se muestran {count} opciones ilustrativas.", zeroResults: "0 opciones ilustrativas", rangeFrom: "Los montos recibidos van de {minimum} a {maximum}.", detailsOpened: "Se abrieron los detalles de {provider}.", detailsClosed: "Se cerraron los detalles del proveedor.", filteredDetailsClosed: "Se cerraron los detalles de {provider} porque no coincide con el filtro.", sortBestExplanation: "El mejor valor equilibra monto recibido, comisión y rapidez entre los resultados ficticios.", sortFeeExplanation: "Ordena por la comisión ilustrativa y luego por el monto recibido.", sortFastestExplanation: "Ordena por el plazo ficticio y luego por el monto recibido.", sortRecipientExplanation: "Ordena por el monto de ejemplo calculado que podría recibir el destinatario." },
  providerDetails: { ...en.providerDetails, profile: "Perfil ilustrativo del proveedor", overview: "Resumen del proveedor", currentOffer: "Oferta ilustrativa actual", capabilities: "Capacidades del servicio", payoutMethods: "Métodos ilustrativos de entrega", digitalAccess: "Acceso digital", supportChannels: "Canales de ayuda", availabilityNote: "Nota de disponibilidad", comparison: "Cómo se compara esta opción", rankingNote: "Solo se consideran los resultados ilustrativos visibles; la posición y las insignias no son recomendaciones.", position: "Posición", feePercentage: "Porcentaje de comisión", recipientDifference: "Diferencia del monto recibido", deliveryPayout: "Entrega y método", importantNotice: "Aviso importante", close: "Cerrar detalles", notice: "Este perfil y todos los valores de la oferta son datos ficticios e ilustrativos, no información en vivo. No se afirma ninguna asociación, integración, verificación, licencia, calificación ni respaldo. TransferHub no inicia transferencias actualmente." },
 marketplace: { ...en.marketplace,
  activeLabel: "Activo",
  clearActiveControls: "Borrar controles activos",
  currencyStatusLabel: "Estado de los datos de moneda",
  currencyStatusVerified: "Verificado",
  currencyStatusNeedsReview: "Necesita revisión",featuredDataNote: "Las tarifas, tasas, estimaciones de entrega, métodos de pago, detalles de proveedores y valores de corredores que se muestran aquí son datos de muestra ilustrativos, no cotizaciones en vivo.",
activeSearch: "Búsqueda",
activeRegion: "Región",
activeSort: "Orden",
activeFavoritesOnly: "Solo favoritos",eyebrow: "EXPLORACIÓN ILUSTRATIVA", title: "Mercado de transferencias", intro: "Explora corredores ilustrativos y las opciones ficticias que el prototipo puede comparar.", disclosure: "Las identidades, comisiones, tasas, plazos, métodos, clasificaciones y valores son datos ficticios, no cotizaciones en vivo.", footer: "La exploración de corredores ilustrativos no implica asociación ni respaldo.", featured: "Corredores ilustrativos destacados", recentlyAdded: "Corredores ilustrativos añadidos recientemente", browseAll: "Explorar todos los corredores", search: "Buscar corredores ilustrativos", searchPlaceholder: "Prueba Canada Haiti o Provider A", clearSearch: "Borrar búsqueda", browseRegion: "Explorar por región",sortLabel: "Ordenar corredores",
sortDefault: "Orden predeterminado",
sortFrom: "País de origen",
sortTo: "País de destino",sortPinned: "Fijados primero", sortRecent: "Vistos recientemente primero", sortFavorites: "Favoritos primero",
sortNewest: "Añadidos recientemente primero", favoritesOnly: "Solo favoritos", allRegions: "Todas las regiones", resultSingle: "1 corredor ilustrativo", resultPlural: "{count} corredores ilustrativos", empty: "Ningún corredor ilustrativo coincide con tu búsqueda.", clearFilters: "Borrar filtros", providerOffers: "Ofertas de proveedores ficticios",corridorDataLabel: "Datos ilustrativos del corredor", payoutMethods: "Métodos ilustrativos de entrega", compare: "Comparar este corredor" },
  workspace: { ...en.workspace, title: "Espacio personal", disclosure: "Los favoritos, corredores fijados y recientes se guardan solo en este navegador para el prototipo. Al borrar los datos del navegador se eliminan y no se sincronizan entre dispositivos.", loading: "Cargando el espacio local…",empty: "Compara un corredor y luego añádelo a favoritos para guardarlo en tu espacio de trabajo local del navegador.", pinned: "Corredores fijados", favorites: "Corredores favoritos", recents: "Corredores vistos recientemente", clearRecents: "Borrar corredores recientes", addFavorite: "Añadir favorito", favorited: "Favorito", removeFavorite: "Quitar favorito", pin: "Fijar corredor", pinnedButton: "Fijado", unpin: "Desfijar corredor", favoriteFirst: "Añade este corredor a favoritos antes de fijarlo.", loadingState: "Cargando estado guardado…" },
  waitlist: { ...en.waitlist, nav: "Navegación de la lista de espera", eyebrow: "NOVEDADES DE ACCESO ANTICIPADO", title: "Sé de los primeros en enterarte.", intro: "Únete para recibir ocasionalmente novedades de TransferHub.", localOnly: "Prototipo de desarrollo: los datos se guardan solo en este navegador y no se envían a un servidor.", email: "Correo electrónico", emailHint: "Lo usaremos solo para novedades ocasionales.", firstName: "Nombre", optional: "opcional", firstNamePlaceholder: "Tu nombre", country: "País de residencia", selectCountry: "Selecciona un país", other: "Otro", consent: "Acepto recibir ocasionalmente novedades de TransferHub por correo. Entiendo que puedo cancelar la suscripción.", submit: "Unirme a la lista", submitting: "Registrando…", noPayment: "No se requiere información de pago. Unirse no crea una cuenta financiera.", emailRequired: "Ingresa tu correo electrónico.", emailInvalid: "Ingresa un correo válido, como nombre@example.com.", consentRequired: "Debes aceptar recibir novedades para unirte.", storageError: "No pudimos guardar el registro en este navegador. Comprueba el almacenamiento e inténtalo de nuevo.", newEyebrow: "ESTÁS EN LA LISTA", duplicateEyebrow: "YA ESTABAS REGISTRADO", thanks: "Gracias por unirte a TransferHub.", already: "Ya estás en la lista de espera.", anotherEmail: "Usar otro correo" },
  countries: { "United States": "Estados Unidos", Canada: "Canadá", France: "Francia", "Dominican Republic": "República Dominicana", Haiti: "Haití" },
  regions: { "North America": "América del Norte", Europe: "Europa", Caribbean: "Caribe" },
  payoutMethods: { "Bank deposit": "Depósito bancario", "Cash pickup": "Retiro en efectivo", "Mobile wallet": "Billetera móvil", "Cash or bank": "Efectivo o banco" },
  workspaceCenter: { ...en.workspaceCenter, metadataTitle: "Mi TransferHub | TransferHub", metadataDescription: "Gestiona favoritos y actividad reciente en este navegador.", navLabel: "Mi TransferHub", eyebrow: "TUS ELEMENTOS EN ESTE NAVEGADOR", title: "Mi TransferHub", intro: "Gestiona los proveedores ficticios y corredores que guardaste o viste en este prototipo.", disclosure: "Los elementos permanecen solo en este navegador. No se sincronizan entre dispositivos y se eliminan al borrar los datos del navegador.", localSummary: "Resumen local de tu navegador", loading: "Cargando tus elementos locales…", empty: "Tu centro de favoritos está listo", emptyDescription: "Guarda un proveedor o corredor ficticio, o compara una ruta, para que aparezca aquí.", pinned: "Corredores fijados", favoriteCorridors: "Corredores favoritos", favoriteProviders: "Proveedores favoritos", recentCorridors: "Corredores recientes", recentProviders: "Proveedores vistos recientemente", clearRecentCorridors: "Borrar corredores recientes", clearRecentProviders: "Borrar proveedores recientes", recentCorridorsCleared: "Corredores recientes borrados.", recentProvidersCleared: "Proveedores recientes borrados.", removeFavorite: "Quitar favorito", removeProviderFavorite: "Quitar proveedor favorito", unpin: "Desfijar corredor", viewCorridors: "Ver corredores disponibles", exploreMarketplace: "Explorar el Mercado", compareOptions: "Comparar opciones de transferencia", payoutCapabilities: "Métodos ilustrativos de entrega", digitalAccess: "Acceso digital", addProviderLabel: "Añadir {provider} a proveedores favoritos", removeProviderLabel: "Quitar {provider} de proveedores favoritos", addProviderText: "Añadir proveedor favorito", providerFavoritedText: "Proveedor favorito", providerAddedStatus: "{provider} añadido a proveedores favoritos.", providerRemovedStatus: "{provider} eliminado de proveedores favoritos.", corridorRemovedStatus: "{corridor} eliminado de favoritos.", corridorUnpinnedStatus: "{corridor} desfijado.", pinnedCountOne: "1 corredor fijado", pinnedCountMany: "{count} corredores fijados", corridorFavoriteCountOne: "1 corredor favorito", corridorFavoriteCountMany: "{count} corredores favoritos", providerFavoriteCountOne: "1 proveedor favorito", providerFavoriteCountMany: "{count} proveedores favoritos", recentCountOne: "1 elemento reciente", recentCountMany: "{count} elementos recientes" },
  providerTrust: { ...en.providerTrust, heading: "Indicadores de confianza y calidad", intro: "Estos indicadores muestran cómo podría presentarse contexto adicional. Son ficticios y no acreditan verificación, trayectoria, cobertura, asistencia ni situación regulatoria real.", sampleLabel: "Datos ilustrativos de ejemplo", verified: "Verificación ilustrativa", verifiedYes: "Se muestra como verificado en esta demostración", verifiedNo: "No se muestra como verificado en esta demostración", yearsInOperation: "Años en operación", yearsValue: "{count} años ilustrativos", countriesServed: "Países atendidos", countriesValue: "{count} países ilustrativos", supportAvailability: "Disponibilidad de asistencia", regulatoryStatus: "Situación regulatoria", lastProfileUpdate: "Última actualización del perfil", businessHours: "Horario comercial ilustrativo", extendedHours: "Horario ampliado ilustrativo", alwaysAvailable: "Disponibilidad ilustrativa las 24 horas", demoRegistration: "Registro de demostración mostrado", demoPending: "Revisión de demostración pendiente", notAssessed: "No evaluado en este prototipo" },
};
