import { en } from "@/lib/i18n/dictionaries/en";
import type { Dictionary } from "@/lib/i18n/types";

export const fr: Dictionary = {
  ...en,
  metadata: { homeTitle: "TransferHub | Une application. Tous vos transferts.", homeDescription: "Explorez des comparaisons fictives et illustratives de transferts d’argent selon les frais, taux de change, modes de versement et délais.", marketplaceTitle: "Marché des transferts | TransferHub", marketplaceDescription: "Explorez les corridors de transfert fictifs du prototype TransferHub.", waitlistTitle: "Rejoindre la liste d’attente | TransferHub", waitlistDescription: "Inscrivez-vous pour recevoir occasionnellement des nouvelles de TransferHub." },
  common: { chooseLanguage: "Choisir la langue", illustrativeUnavailable: "Informations illustratives sur le prestataire indisponibles", fictionalProviders: "Prestataires et valeurs fictifs", sampleScenario: "Scénario d’exemple.", actualValuesMayDiffer: "Les frais, taux, disponibilités, modes de versement et délais réels peuvent varier. TransferHub n’effectue actuellement aucun transfert.", copyright: "© 2026 TransferHub.info." },
  navigation: { primary: "Navigation principale", menu: "Ouvrir le menu de navigation", home: "Accueil", marketplace: "Marché", features: "Fonctionnalités", howItWorks: "Fonctionnement", about: "À propos", faq: "FAQ", waitlist: "Liste d’attente", joinWaitlist: "S’inscrire", signIn: "Connexion", comingSoon: "bientôt disponible", backHome: "Retour à l’accueil" },
  homepage: {
    hero: { eyebrow: "CONÇU POUR LES FAMILLES DU MONDE ENTIER", titleStart: "Une application.", titleEmphasis: "Tous vos transferts.", description: "Découvrez comment comparer les options de transfert selon les frais, taux de change, modes de versement et délais. Tous les résultats actuels sont fictifs et illustratifs.", launchNote: "Aucun transfert requis. Soyez parmi les premiers informés du lancement." },
    features: { eyebrow: "TOUT AU MÊME ENDROIT", title: "Plus de clarté avant d’envoyer", description: "TransferHub est conçu pour rendre la comparaison des options de transfert plus simple, plus rapide et plus facile à comprendre.", items: [
      { id: "fee", title: "Comparer les frais", description: "Consultez côte à côte des frais de transfert illustratifs avant de choisir une option." },
      { id: "rate", title: "Vérifier les taux de change", description: "Comprenez comment le taux peut modifier le montant reçu par votre destinataire." },
      { id: "speed", title: "Examiner la rapidité", description: "Comparez les délais estimés, de quelques minutes à plusieurs jours." },
      { id: "wallet", title: "Explorer les modes de versement", description: "Examinez les options potentielles de dépôt bancaire, retrait d’espèces et portefeuille mobile." },
      { id: "people", title: "Enregistrer les destinataires", description: "Gardez leurs informations organisées pour simplifier votre prochaine utilisation." },
      { id: "track", title: "Suivre les transferts", description: "Suivez la progression d’un transfert dans une vue claire et facile à comprendre." },
    ] },
    howItWorks: { eyebrow: "LA SIMPLICITÉ AVANT TOUT", title: "Comment fonctionnera TransferHub", description: "Un parcours plus clair, de la décision à la livraison, sans passer d’un onglet à l’autre.", steps: [
      { id: "enter", number: "01", title: "Saisissez votre transfert", description: "Choisissez le pays d’envoi, la destination et le montant." }, { id: "compare", number: "02", title: "Comparez vos options", description: "Examinez les détails illustratifs selon les critères qui comptent pour vous." }, { id: "choose", number: "03", title: "Choisissez en confiance", description: "Sélectionnez votre option préférée lorsque des connexions autorisées seront disponibles." },
    ] },
    about: { eyebrow: "UNE RÉFLEXION DÈS LE DÉPART", titleStart: "Conçu pour la sécurité.", titleEnd: "Bâti pour la transparence.", description: "TransferHub est conçu en tenant compte de la sécurité, de la vie privée et d’un étiquetage transparent des données. Les informations illustratives seront clairement distinguées des données vérifiées.", learnMore: "En savoir plus sur notre approche", items: [
      { id: "shield", title: "Conception axée sur la sécurité", description: "Des mesures de protection seront envisagées pendant tout le développement." }, { id: "eye", title: "Libellés de données clairs", description: "Les données d’aperçu, illustratives et autorisées seront clairement identifiées." }, { id: "lock", title: "Respect de la vie privée", description: "Nous souhaitons recueillir uniquement les informations nécessaires." }, { id: "check", title: "Aucun soutien implicite", description: "Les fiches de prestataires ne laisseront pas entendre l’existence de partenariats inexistants." },
    ] },
    roadmap: { eyebrow: "CE QUE NOUS CONSTRUISONS", title: "La suite du parcours", description: "Une progression réfléchie vers une comparaison des transferts plus claire.", items: [
      { id: "website", number: "01", title: "Site et liste d’attente", timing: "Maintenant", status: "En ligne" }, { id: "comparison", number: "02", title: "Plateforme de comparaison", timing: "Prochaine étape", status: "En conception" }, { id: "providers", number: "03", title: "Intégrations autorisées", timing: "Plus tard", status: "Planifié" }, { id: "mobile", number: "04", title: "Applications mobiles", timing: "À l’avenir", status: "Planifié" },
    ] },
    faq: { eyebrow: "QUESTIONS ET RÉPONSES", title: "Questions fréquentes", description: "Ce qu’il faut savoir pendant que TransferHub prend forme.", items: [
      { id: "what", question: "Qu’est-ce que TransferHub ?", answer: "TransferHub est une plateforme de comparaison en développement qui vise à regrouper les options de transfert, avec Haïti comme priorité initiale." }, { id: "send", question: "Puis-je envoyer de l’argent avec TransferHub aujourd’hui ?", answer: "Non. La version 0.1.0 est un prototype interactif et une liste d’attente de développement. L’envoi nécessiterait des connexions autorisées et des protections supplémentaires." }, { id: "partners", question: "TransferHub est-il partenaire des prestataires affichés ?", answer: "Aucun partenariat ni aucune intégration n’est revendiqué. Toutes les données d’aperçu restent illustratives tant qu’aucune connexion autorisée n’existe." }, { id: "comparison", question: "Comment fonctionneront les comparaisons ?", answer: "La plateforme organisera les frais, taux, modes de versement et délais afin de permettre une consultation côte à côte." }, { id: "countries", question: "TransferHub prendra-t-il en charge d’autres pays qu’Haïti ?", answer: "Haïti est la priorité initiale. D’autres corridors pourront être envisagés lorsque des données fiables seront disponibles." }, { id: "access", question: "Comment obtenir un accès anticipé ?", answer: "Inscrivez-vous à la liste d’attente pour recevoir occasionnellement des nouvelles du produit." },
    ] },
    footer: { taglineStart: "Une application. Tous vos transferts.", taglineEnd: "La comparaison des transferts, en plus clair.", navigationLabel: "Navigation du pied de page", privacy: "Vie privée", terms: "Conditions", security: "Sécurité", contact: "Contact", about: "À propos", rights: "© 2026 TransferHub.info. Tous droits réservés.", disclosure: "Les informations présentées sont illustratives et n’impliquent aucun partenariat ni soutien." },
  },
  comparison: { ...en.comparison, findOptions: "Trouvez vos options", compareTransfer: "Comparer un transfert", fromCountry: "Pays d’envoi", toCountry: "Pays de destination", amountToSend: "Montant à envoyer", amountHelp: "Saisissez entre 10 et 10 000 {currency}, avec au plus deux décimales.", quickAmounts: "Montants rapides en {currency}", compareOptions: "Comparer les options", comparing: "Comparaison…", swapCountries: "Inverser les pays", swapLabel: "Inverser les pays de transfert : {from} et {to}", swapTitle: "Inverser l’origine et la destination", reverseUnavailable: "Le corridor inverse n’est pas disponible.", preview: "Aperçu de la comparaison", youSend: "Vous envoyez", sampleBanner: "DONNÉES D’EXEMPLE ILLUSTRATIVES — PAS DE DEVIS EN DIRECT", payoutMethod: "Mode de versement", allPayoutMethods: "Tous les modes", bankDeposit: "Dépôt bancaire", cashPickup: "Retrait d’espèces", mobileWallet: "Portefeuille mobile", cashOrBank: "Espèces ou banque", sortBy: "Trier par", bestValue: "Meilleur rapport", lowestFee: "Frais les plus bas", fastest: "Plus rapide", highestRecipient: "Montant reçu le plus élevé", provider: "Prestataire", fee: "Frais", rate: "Taux", delivery: "Délai", payout: "Versement", recipientGets: "Le destinataire reçoit", actions: "Actions", viewDetails: "Voir les détails", detailsOpen: "Détails ouverts", noFilterResults: "Aucune option illustrative ne correspond à ce filtre.", clearFilter: "Effacer le filtre", loading: "Création de votre comparaison d’exemple…", unavailable: "Comparaison illustrative indisponible", unavailableMessage: "Ce corridor illustratif ne figure pas dans les données fictives actuelles.", enterAmount: "Saisissez un montant à envoyer.", invalidAmount: "Saisissez un montant valide avec au plus deux décimales.", minimumAmount: "Saisissez au moins 10 {currency}.", maximumAmount: "Ne dépassez pas 10 000 {currency}.", notUpdated: "Comparaison non mise à jour. Corrigez le montant et réessayez.", comparingStatus: "Comparaison des options illustratives.", readyStatus: "Comparaison prête pour {amount} de {from} vers {to}.", resultSingle: "1 option illustrative affichée.", resultPlural: "{count} options illustratives affichées.", zeroResults: "0 option illustrative", rangeFrom: "Les montants reçus vont de {minimum} à {maximum}.", detailsOpened: "Détails de {provider} ouverts.", detailsClosed: "Détails du prestataire fermés.", filteredDetailsClosed: "Détails de {provider} fermés car ce prestataire ne correspond pas au filtre.", sortBestExplanation: "Le meilleur rapport équilibre montant reçu, frais et rapidité parmi les résultats fictifs.", sortFeeExplanation: "Trie d’abord selon les frais illustratifs, puis le montant reçu.", sortFastestExplanation: "Trie selon le délai fictif, puis le montant reçu.", sortRecipientExplanation: "Trie selon le montant d’exemple calculé que le destinataire pourrait recevoir." },
  providerDetails: { ...en.providerDetails, profile: "Profil illustratif du prestataire", overview: "Présentation du prestataire", currentOffer: "Offre illustrative actuelle", capabilities: "Capacités du service", payoutMethods: "Modes de versement illustratifs", digitalAccess: "Accès numérique", supportChannels: "Canaux d’assistance", availabilityNote: "Note de disponibilité", comparison: "Comparaison de cette option", rankingNote: "Résultats illustratifs visibles uniquement ; la position et les badges ne sont pas des recommandations.", position: "Position", feePercentage: "Pourcentage de frais", recipientDifference: "Écart du montant reçu", deliveryPayout: "Délai et versement", importantNotice: "Avis important", close: "Fermer les détails", notice: "Ce profil et toutes les valeurs de l’offre sont des données fictives et illustratives, pas des informations en direct. Aucun partenariat, intégration, contrôle, agrément, classement ou soutien n’est revendiqué. TransferHub n’effectue actuellement aucun transfert." },
  marketplace: { ...en.marketplace, eyebrow: "DÉCOUVERTE ILLUSTRATIVE", title: "Marché des transferts", intro: "Explorez les corridors illustratifs disponibles et les options fictives que le prototype peut comparer.", disclosure: "Les prestataires, frais, taux, délais, modes de versement, classements et valeurs sont des exemples fictifs, pas des devis en direct.", footer: "La présentation de corridors illustratifs n’implique aucun partenariat ni soutien.", featured: "Corridors illustratifs en vedette", recentlyAdded: "Corridors illustratifs récemment ajoutés", browseAll: "Parcourir tous les corridors", search: "Rechercher des corridors illustratifs", searchPlaceholder: "Essayez Canada Haïti ou Provider A", clearSearch: "Effacer la recherche", browseRegion: "Parcourir par région",sortLabel: "Trier les corridors",
sortDefault: "Ordre par défaut",
sortFrom: "Pays d’origine",
sortTo: "Pays de destination",sortPinned: "Épinglés en premier", sortRecent: "Récemment consultés en premier",sortFavorites: "Favoris en premier",sortNewest: "Ajoutés récemment en premier", favoritesOnly: "Favoris uniquement", allRegions: "Toutes les régions", resultSingle: "1 corridor illustratif", resultPlural: "{count} corridors illustratifs", empty: "Aucun corridor illustratif ne correspond à votre recherche.", clearFilters: "Effacer les filtres", providerOffers: "Offres de prestataires fictifs", payoutMethods: "Modes de versement illustratifs", compare: "Comparer ce corridor" },
  workspace: { ...en.workspace, title: "Espace personnel", disclosure: "Les favoris, corridors épinglés et récents sont enregistrés uniquement dans ce navigateur pour ce prototype. Effacer les données du navigateur les supprime ; ils ne sont pas synchronisés.", loading: "Chargement de l’espace local…", empty: "Ajoutez un corridor aux favoris pour créer votre espace local.", pinned: "Corridors épinglés", favorites:  "Corridors favoris", recents: "Corridors consultés récemment", clearRecents: "Effacer les corridors récents", addFavorite: "Ajouter aux favoris", favorited: "Favori", removeFavorite: "Retirer des favoris", pin: "Épingler", pinnedButton: "Épinglé", unpin: "Désépingler", favoriteFirst: "Ajoutez d’abord ce corridor aux favoris.", loadingState: "Chargement de l’état enregistré…" },
  waitlist: { ...en.waitlist, nav: "Navigation de la liste d’attente", eyebrow: "NOUVELLES SUR L’ACCÈS ANTICIPÉ", title: "Soyez parmi les premiers informés.", intro: "Inscrivez-vous pour recevoir occasionnellement des nouvelles de TransferHub.", localOnly: "Prototype de développement : les données sont stockées uniquement dans ce navigateur et ne sont envoyées à aucun serveur.", email: "Adresse courriel", emailHint: "Nous l’utiliserons uniquement pour des nouvelles occasionnelles.", firstName: "Prénom", optional: "facultatif", firstNamePlaceholder: "Votre prénom", country: "Pays de résidence", selectCountry: "Choisir un pays", other: "Autre", consent: "J’accepte de recevoir occasionnellement des nouvelles de TransferHub par courriel. Je pourrai me désabonner.", submit: "Rejoindre la liste", submitting: "Inscription…", noPayment: "Aucune information de paiement n’est requise. L’inscription ne crée pas de compte financier.", emailRequired: "Saisissez votre adresse courriel.", emailInvalid: "Saisissez une adresse valide, par exemple nom@example.com.", consentRequired: "Vous devez accepter les nouvelles pour vous inscrire.", storageError: "Impossible d’enregistrer l’inscription dans ce navigateur. Vérifiez le stockage et réessayez.", newEyebrow: "VOUS ÊTES INSCRIT", duplicateEyebrow: "DÉJÀ INSCRIT", thanks: "Merci de rejoindre TransferHub.", already: "Vous êtes déjà sur la liste.", anotherEmail: "Utiliser une autre adresse" },
  countries: { "United States": "États-Unis", Canada: "Canada", France: "France", "Dominican Republic": "République dominicaine", Haiti: "Haïti" },
  regions: { "North America": "Amérique du Nord", Europe: "Europe", Caribbean: "Caraïbes" },
  payoutMethods: { "Bank deposit": "Dépôt bancaire", "Cash pickup": "Retrait d’espèces", "Mobile wallet": "Portefeuille mobile", "Cash or bank": "Espèces ou banque" },
  workspaceCenter: { ...en.workspaceCenter, metadataTitle: "Mon TransferHub | TransferHub", metadataDescription: "Gérez vos favoris et activités récentes dans ce navigateur.", navLabel: "Mon TransferHub", eyebrow: "VOS ÉLÉMENTS DANS CE NAVIGATEUR", title: "Mon TransferHub", intro: "Gérez les prestataires fictifs et corridors enregistrés ou consultés dans ce prototype.", disclosure: "Les éléments restent uniquement dans ce navigateur. Ils ne sont pas synchronisés entre appareils et disparaissent si vous effacez les données du navigateur.", localSummary: "Résumé local de votre navigateur", loading: "Chargement de vos éléments locaux…", empty: "Votre espace de favoris est prêt", emptyDescription: "Enregistrez un prestataire fictif ou un corridor, ou comparez un trajet pour le retrouver ici.", pinned: "Corridors épinglés", favoriteCorridors: "Corridors favoris", favoriteProviders: "Prestataires favoris", recentCorridors: "Corridors récents", recentProviders: "Prestataires consultés récemment", clearRecentCorridors: "Effacer les corridors récents", clearRecentProviders: "Effacer les prestataires récents", recentCorridorsCleared: "Corridors récents effacés.", recentProvidersCleared: "Prestataires récents effacés.", removeFavorite: "Retirer des favoris", removeProviderFavorite: "Retirer le prestataire favori", unpin: "Désépingler le corridor", viewCorridors: "Voir les corridors disponibles", exploreMarketplace: "Explorer le marché", compareOptions: "Comparer les options de transfert", payoutCapabilities: "Modes de versement illustratifs", digitalAccess: "Accès numérique", addProviderLabel: "Ajouter {provider} aux prestataires favoris", removeProviderLabel: "Retirer {provider} des prestataires favoris", addProviderText: "Ajouter aux favoris", providerFavoritedText: "Prestataire favori", providerAddedStatus: "{provider} ajouté aux prestataires favoris.", providerRemovedStatus: "{provider} retiré des prestataires favoris.", corridorRemovedStatus: "{corridor} retiré des favoris.", corridorUnpinnedStatus: "{corridor} désépinglé.", pinnedCountOne: "1 corridor épinglé", pinnedCountMany: "{count} corridors épinglés", corridorFavoriteCountOne: "1 corridor favori", corridorFavoriteCountMany: "{count} corridors favoris", providerFavoriteCountOne: "1 prestataire favori", providerFavoriteCountMany: "{count} prestataires favoris", recentCountOne: "1 élément récent", recentCountMany: "{count} éléments récents" },
  providerTrust: { ...en.providerTrust, heading: "Indicateurs de confiance et de qualité", intro: "Ces indicateurs montrent comment un contexte supplémentaire pourrait apparaître. Ils sont fictifs et ne prouvent aucune vérification, ancienneté, couverture, assistance ou situation réglementaire réelle.", sampleLabel: "Données d’exemple illustratives", verified: "Vérification illustrative", verifiedYes: "Présenté comme vérifié dans cette démo", verifiedNo: "Non présenté comme vérifié dans cette démo", yearsInOperation: "Années d’activité", yearsValue: "{count} années illustratives", countriesServed: "Pays desservis", countriesValue: "{count} pays illustratifs", supportAvailability: "Disponibilité de l’assistance", regulatoryStatus: "Situation réglementaire", lastProfileUpdate: "Dernière mise à jour du profil", businessHours: "Heures ouvrables illustratives", extendedHours: "Horaires étendus illustratifs", alwaysAvailable: "Disponibilité illustrative 24 h/24", demoRegistration: "Enregistrement de démonstration affiché", demoPending: "Examen de démonstration en attente", notAssessed: "Non évalué dans ce prototype" },
};
