import { en } from "@/lib/i18n/dictionaries/en";
import type { Dictionary } from "@/lib/i18n/types";

export const ht: Dictionary = {
  ...en,
  metadata: { homeTitle: "TransferHub | Yon aplikasyon. Tout transfè yo.", homeDescription: "Gade konparezon transfè lajan ki envante pou egzanp, tankou frè, to chanj, fason pou resevwa ak delè.", marketplaceTitle: "Mache transfè | TransferHub", marketplaceDescription: "Gade koridò transfè ki envante nan pwototip TransferHub la.", waitlistTitle: "Antre nan lis datant lan | TransferHub", waitlistDescription: "Antre nan lis TransferHub la pou resevwa nouvèl sou pwodwi a detanzantan." },
  common: { chooseLanguage: "Chwazi lang", illustrativeUnavailable: "Enfòmasyon egzanp sou founisè a pa disponib", fictionalProviders: "Founisè ak valè ki envante", sampleScenario: "Egzanp senaryo.", actualValuesMayDiffer: "Vrè frè, to, disponiblite, fason pou resevwa ak delè ka diferan. TransferHub poko fè transfè lajan.", copyright: "© 2026 TransferHub.info." },
  navigation: { primary: "Navigasyon prensipal", menu: "Louvri meni navigasyon an", home: "Akèy", marketplace: "Mache", features: "Fonksyon", howItWorks: "Kijan li mache", about: "Konsènan", faq: "Kesyon", waitlist: "Lis datant", joinWaitlist: "Antre nan lis la", signIn: "Konekte", comingSoon: "ap vini", backHome: "Retounen akèy" },
  homepage: {
    hero: { eyebrow: "FÈ POU FANMI TOUPATOU NAN LEMONN", titleStart: "Yon aplikasyon.", titleEmphasis: "Tout transfè yo.", description: "Gade kijan yo ta ka konpare opsyon transfè lajan selon frè, to chanj, fason pou resevwa ak delè. Tout rezilta aktyèl yo se egzanp ki envante.", launchNote: "Ou pa bezwen fè transfè. Pami premye moun ki konnen lè nou lanse." },
    features: { eyebrow: "TOUT BAGAY NAN YON SÈL KOTE", title: "Konprann anvan ou voye", description: "N ap bati TransferHub pou fè konpare opsyon transfè yo pi senp, pi rapid epi pi fasil pou konprann.", items: [
      { id: "fee", title: "Konpare frè yo", description: "Gade frè transfè egzanp yo kòtakòt anvan ou chwazi yon opsyon." },
      { id: "rate", title: "Tcheke to chanj yo", description: "Konprann kijan to a ka chanje kantite moun k ap resevwa a jwenn." },
      { id: "speed", title: "Gade vitès livrezon an", description: "Konpare delè livrezon yo, soti nan kèk minit rive nan plizyè jou." },
      { id: "wallet", title: "Gade fason pou resevwa", description: "Gade opsyon depo labank, pran lajan kach ak bous mobil." },
      { id: "people", title: "Sere moun k ap resevwa yo", description: "Kenbe enfòmasyon moun k ap resevwa yo òganize pou pwochen fwa a pi fasil." },
      { id: "track", title: "Swiv transfè yo", description: "Swiv pwogrè transfè a nan yon fason ki klè epi fasil pou konprann." },
    ] },
    howItWorks: { eyebrow: "SENP DEPI NAN KONSEPSYON", title: "Kijan TransferHub pral mache", description: "Yon chemen ki pi klè soti nan desizyon rive nan livrezon, san ou pa sote ant plizyè paj.", steps: [
      { id: "enter", number: "01", title: "Antre transfè ou a", description: "Chwazi kote lajan an soti, kote li prale ak kantite a." }, { id: "compare", number: "02", title: "Konpare opsyon ou yo", description: "Gade detay egzanp sou founisè yo selon sa ki enpòtan pou ou." }, { id: "choose", number: "03", title: "Chwazi ak konfyans", description: "Chwazi opsyon ou prefere a lè koneksyon founisè otorize yo disponib." },
    ] },
    about: { eyebrow: "N AP REFLECHI DEPI NAN KÒMANSMAN", titleStart: "Fèt ak sekirite nan tèt nou.", titleEnd: "Bati pou transparans.", description: "N ap konsevwa TransferHub ak sekirite, vi prive ak etikèt done ki klè. N ap toujou separe enfòmasyon egzanp ak done founisè ki verifye.", learnMore: "Aprann plis sou apwòch nou", items: [
      { id: "shield", title: "Konsepsyon ki panse ak sekirite", description: "N ap konsidere pwoteksyon pandan tout devlopman pwodwi a." }, { id: "eye", title: "Etikèt done ki klè", description: "N ap make byen klè done aperçu, egzanp ak done otorize." }, { id: "lock", title: "Vi prive nan tèt nou", description: "Nou vle ranmase sèlman sa eksperyans lan bezwen." }, { id: "check", title: "Pa gen apwobasyon kache", description: "Lis founisè yo pap fè kwè gen patenarya ki pa egziste." },
    ] },
    roadmap: { eyebrow: "SA N AP BATI", title: "Wout ki devan an", description: "Yon chemen reflechi pou rann konparezon transfè yo pi klè.", items: [
      { id: "website", number: "01", title: "Sit entènèt ak lis datant", timing: "Kounye a", status: "Anliy" }, { id: "comparison", number: "02", title: "Platfòm konparezon", timing: "Apre sa", status: "N ap konsevwa" }, { id: "providers", number: "03", title: "Entegrasyon founisè otorize", timing: "Pita", status: "Planifye" }, { id: "mobile", number: "04", title: "Aplikasyon mobil", timing: "Alavni", status: "Planifye" },
    ] },
    faq: { eyebrow: "KESYON AK REPONS", title: "Kesyon moun poze souvan", description: "Sa pou konnen pandan TransferHub ap pran fòm.", items: [
      { id: "what", question: "Kisa TransferHub ye?", answer: "TransferHub se yon platfòm konparezon n ap devlope pou ede moun gade opsyon transfè lajan nan yon sèl kote, ak Ayiti kòm premye konsantrasyon." }, { id: "send", question: "Èske mwen ka voye lajan ak TransferHub jodi a?", answer: "Non. Vèsyon 0.1.0 se yon pwototip konparezon ak yon lis datant pou devlopman. Pou fè transfè, fòk gen koneksyon founisè otorize ak plis pwoteksyon." }, { id: "partners", question: "Èske TransferHub se patnè founisè yo?", answer: "Nou pa pretann gen patenarya oswa entegrasyon. Tout done aperçu sou sit la se egzanp jiskaske gen koneksyon done otorize." }, { id: "comparison", question: "Kijan konparezon yo pral mache?", answer: "Platfòm lan pral òganize frè, to chanj, fason pou resevwa ak delè pou moun ka gade opsyon yo kòtakòt." }, { id: "countries", question: "Èske TransferHub pral sipòte lòt peyi pase Ayiti?", answer: "Ayiti se premye konsantrasyon an. Nou ka ajoute lòt koridò lè platfòm lan grandi epi done serye disponib." }, { id: "access", question: "Kijan mwen ka jwenn aksè bonè?", answer: "Antre nan lis datant lan pou resevwa nouvèl sou pwodwi a ak aksè bonè." },
    ] },
    footer: { taglineStart: "Yon aplikasyon. Tout transfè yo.", taglineEnd: "Konpare transfè pi klè.", navigationLabel: "Navigasyon anba paj", privacy: "Vi prive", terms: "Kondisyon", security: "Sekirite", contact: "Kontak", about: "Konsènan", rights: "© 2026 TransferHub.info. Tout dwa rezève.", disclosure: "Enfòmasyon sou founisè yo se egzanp epi yo pa vle di gen patenarya oswa apwobasyon." },
  },
  comparison: { ...en.comparison, findOptions: "Jwenn opsyon ou yo", compareTransfer: "Konpare yon transfè", fromCountry: "Peyi kote lajan soti", toCountry: "Peyi kote lajan prale", amountToSend: "Kantite pou voye", amountHelp: "Antre ant 10 ak 10,000 {currency}, ak omwen de chif apre pwen.", quickAmounts: "Kantite rapid an {currency}", compareOptions: "Konpare opsyon transfè yo", comparing: "N ap konpare…", swapCountries: "Chanje peyi yo", swapLabel: "Chanje peyi transfè yo: {from} ak {to}", swapTitle: "Chanje kote lajan soti ak kote li prale", reverseUnavailable: "Koridò nan sans opoze a pa disponib.", preview: "Apèsi konparezon", youSend: "Ou voye", sampleBanner: "DONE EGZANP KI ENVANTE — SE PA PRI AN DIRÈK", payoutMethod: "Fason pou resevwa", allPayoutMethods: "Tout fason yo", bankDeposit: "Depo labank", cashPickup: "Pran lajan kach", mobileWallet: "Bous mobil", cashOrBank: "Lajan kach oswa bank", sortBy: "Klase pa", bestValue: "Pi bon valè", lowestFee: "Frè ki pi ba", fastest: "Pi rapid", highestRecipient: "Pi gwo kantite moun nan resevwa", provider: "Founisè", fee: "Frè", rate: "To", delivery: "Delè", payout: "Resevwa", recipientGets: "Moun nan resevwa", actions: "Aksyon", viewDetails: "Gade detay", detailsOpen: "Detay louvri", noFilterResults: "Pa gen opsyon egzanp ki mache ak filtè sa a.", clearFilter: "Efase filtè", loading: "N ap prepare konparezon egzanp lan…", unavailable: "Konparezon egzanp lan pa disponib", unavailableMessage: "Koridò sa a pa nan done egzanp ki envante yo.", enterAmount: "Antre yon kantite pou voye.", invalidAmount: "Antre yon kantite ki valab ak pa plis pase de chif apre pwen.", minimumAmount: "Antre omwen 10 {currency}.", maximumAmount: "Pa antre plis pase 10,000 {currency}.", notUpdated: "Konparezon an pa chanje. Korije kantite a epi eseye ankò.", comparingStatus: "N ap konpare opsyon transfè egzanp yo.", readyStatus: "Konparezon pare pou {amount} soti {from} pou ale {to}.", resultSingle: "N ap montre 1 opsyon egzanp.", resultPlural: "N ap montre {count} opsyon egzanp.", zeroResults: "0 opsyon egzanp", rangeFrom: "Kantite moun nan resevwa soti nan {minimum} rive {maximum}.", detailsOpened: "Detay {provider} louvri.", detailsClosed: "Detay founisè a fèmen.", filteredDetailsClosed: "Detay {provider} fèmen paske li pa mache ak filtè a.", sortBestExplanation: "Pi bon valè a balanse kantite moun nan resevwa, frè ak vitès nan rezilta ki envante yo.", sortFeeExplanation: "Klase selon frè egzanp ki pi ba, apre sa kantite moun nan resevwa.", sortFastestExplanation: "Klase selon delè ki pi kout, apre sa kantite moun nan resevwa.", sortRecipientExplanation: "Klase selon kantite egzanp moun nan ka resevwa." },
  providerDetails: { ...en.providerDetails, profile: "Pwofil founisè pou egzanp", overview: "Apèsi sou founisè a", currentOffer: "Òf egzanp aktyèl", capabilities: "Sa sèvis la ka fè", payoutMethods: "Fason egzanp pou resevwa", digitalAccess: "Aksè dijital", supportChannels: "Fason pou jwenn asistans", availabilityNote: "Nòt sou disponiblite", comparison: "Kijan opsyon sa a konpare", rankingNote: "Se sèlman rezilta egzanp ki parèt yo; pozisyon ak badj yo pa rekòmandasyon.", position: "Pozisyon", feePercentage: "Pousantaj frè", recipientDifference: "Diferans kantite moun nan resevwa", deliveryPayout: "Delè ak fason pou resevwa", importantNotice: "Avi enpòtan", close: "Fèmen detay", notice: "Pwofil sa a ak tout valè òf yo se done egzanp ki envante, se pa enfòmasyon an dirèk. Nou pa pretann gen patenarya, entegrasyon, verifikasyon, lisans, klasman oswa apwobasyon. TransferHub poko fè transfè lajan." },
marketplace: { ...en.marketplace, sortLabel: "Klase koridò yo", 
activeLabel: "Aktif",
clearActiveControls: "Efase kontwòl aktif yo",
currencyStatusLabel: "Estati done lajan",
currencyStatusVerified: "Verifye",
currencyStatusNeedsReview: "Bezwen revizyon",featuredDataNote: "Frè, to, estimasyon livrezon, metòd peman, detay founisè, ak valè koridò ki parèt isit la se done echantiyon ilistratif, se pa sitasyon an dirèk.",
activeSearch: "Rechèch",
activeRegion: "Rejyon",
activeSort: "Triye",
activeFavoritesOnly: "Favori sèlman",
sortDefault: "Lòd nòmal",
sortFrom: "Peyi depa",
sortTo: "Peyi destinasyon",sortPinned: "Epingle yo an premye",sortRecent: "Dènye koridò yo wè an premye",sortFavorites: "Favori yo an premye",sortNewest: "Dènye ajoute yo an premye", favoritesOnly: "Favori sèlman", eyebrow: "DEKOUVÈT POU EGZANP", title: "Mache transfè", intro: "Gade koridò egzanp ki disponib ak opsyon ki envante pwototip la ka konpare.", disclosure: "Tout non founisè, frè, to, delè, fason pou resevwa, klasman ak valè koridò yo se done ki envante, se pa pri an dirèk.", footer: "Koridò egzanp yo pa vle di gen patenarya oswa apwobasyon.", featured: "Koridò egzanp nou mete devan", recentlyAdded: "Koridò egzanp ki fèk ajoute", browseAll: "Gade tout koridò yo", search: "Chèche koridò egzanp", searchPlaceholder: "Eseye Canada Haiti oswa Provider A", clearSearch: "Efase rechèch", browseRegion: "Gade pa rejyon", allRegions: "Tout rejyon", resultSingle: "1 koridò egzanp", resultPlural: "{count} koridò egzanp", empty: "Pa gen koridò egzanp ki mache ak rechèch ou a.", clearFilters: "Efase filtè yo", providerOffers: "Òf founisè ki envante", payoutMethods: "Fason egzanp pou resevwa", compare: "Konpare koridò sa a" },
  workspace: { ...en.workspace, title: "Espas pèsonèl", disclosure: "Favori, wout epingle ak koridò resan yo sere sèlman nan navigatè sa a pou pwototip la. Si ou efase done navigatè a, yo disparèt; yo pa senkronize sou lòt aparèy.", loading: "N ap chaje espas navigatè a…", empty: "Mete yon koridò nan favori pou bati espas ou.", pinned: "Koridò epingle", favorites: "Koridò favori", recents: "Koridò ou fèk gade", clearRecents: "Efase koridò resan yo", addFavorite: "Ajoute nan favori", favorited: "Favori", removeFavorite: "Retire nan favori", pin: "Epingle koridò", pinnedButton: "Epingle", unpin: "Retire epeng", favoriteFirst: "Mete koridò sa a nan favori anvan ou epingle li.", loadingState: "N ap chaje sa ki te sere…" },
  waitlist: { ...en.waitlist, nav: "Navigasyon lis datant", eyebrow: "NOUVÈL SOU AKSÈ BONÈ", title: "Se pou ou pami premye moun ki konnen.", intro: "Antre nan lis TransferHub la pou resevwa nouvèl sou pwodwi a detanzantan.", localOnly: "Pwototip devlopman: enfòmasyon yo sere sèlman nan navigatè sa a; yo pa voye sou okenn sèvè.", email: "Adrès imèl", emailHint: "N ap sèvi avè l sèlman pou nouvèl pwodwi detanzantan.", firstName: "Prenon", optional: "si ou vle", firstNamePlaceholder: "Prenon ou", country: "Peyi kote ou rete", selectCountry: "Chwazi yon peyi", other: "Lòt", consent: "Mwen dakò resevwa nouvèl TransferHub detanzantan pa imèl. Mwen ka dezabòne pita.", submit: "Antre nan lis la", submitting: "N ap enskri ou…", noPayment: "Nou pa mande enfòmasyon peman. Enskripsyon an pa kreye yon kont finansye.", emailRequired: "Antre adrès imèl ou.", emailInvalid: "Antre yon adrès imèl ki valab, tankou non@example.com.", consentRequired: "Ou dwe dakò resevwa nouvèl pou antre nan lis la.", storageError: "Nou pa t ka sere enskripsyon an nan navigatè sa a. Verifye depo navigatè a epi eseye ankò.", newEyebrow: "OU NAN LIS LA", duplicateEyebrow: "OU TE DEJA ENSKRI", thanks: "Mèsi paske ou antre nan TransferHub.", already: "Ou deja nan lis datant lan.", anotherEmail: "Sèvi ak yon lòt imèl" },
  countries: { "United States": "Etazini", Canada: "Kanada", France: "Lafrans", "Dominican Republic": "Repiblik Dominikèn", Haiti: "Ayiti" },
  regions: { "North America": "Amerik di Nò", Europe: "Ewòp", Caribbean: "Karayib" },
  payoutMethods: { "Bank deposit": "Depo labank", "Cash pickup": "Pran lajan kach", "Mobile wallet": "Bous mobil", "Cash or bank": "Lajan kach oswa bank" },
  workspaceCenter: { ...en.workspaceCenter, metadataTitle: "TransferHub pa mwen | TransferHub", metadataDescription: "Jere favori ak aktivite resan nan navigatè sa a.", navLabel: "TransferHub pa mwen", eyebrow: "SA OU SERE NAN NAVIGATÈ SA A", title: "TransferHub pa mwen", intro: "Jere founisè ki envante ak koridò ou sere oswa gade nan pwototip sa a.", disclosure: "Sa ou sere rete sèlman nan navigatè sa a. Yo pa senkronize sou lòt aparèy, epi yo disparèt si ou efase done navigatè a.", localSummary: "Rezime lokal navigatè ou", loading: "N ap chaje sa ou sere yo…", empty: "Sant favori ou pare", emptyDescription: "Sere yon founisè oswa koridò ki envante, oswa konpare yon wout, pou li parèt isit la.", pinned: "Koridò epingle", favoriteCorridors: "Koridò favori", favoriteProviders: "Founisè favori", recentCorridors: "Koridò resan", recentProviders: "Founisè ou fèk gade", clearRecentCorridors: "Efase koridò resan yo", clearRecentProviders: "Efase founisè resan yo", recentCorridorsCleared: "Koridò resan yo efase.", recentProvidersCleared: "Founisè resan yo efase.", removeFavorite: "Retire nan favori", removeProviderFavorite: "Retire founisè favori", unpin: "Retire epeng koridò a", viewCorridors: "Gade koridò ki disponib", exploreMarketplace: "Gade Mache a", compareOptions: "Konpare opsyon transfè", payoutCapabilities: "Fason egzanp pou resevwa", digitalAccess: "Aksè dijital", addProviderLabel: "Ajoute {provider} nan founisè favori", removeProviderLabel: "Retire {provider} nan founisè favori", addProviderText: "Ajoute founisè favori", providerFavoritedText: "Founisè favori", providerAddedStatus: "{provider} ajoute nan founisè favori.", providerRemovedStatus: "{provider} retire nan founisè favori.", corridorRemovedStatus: "{corridor} retire nan favori.", corridorUnpinnedStatus: "Yo retire epeng {corridor}.", pinnedCountOne: "1 koridò epingle", pinnedCountMany: "{count} koridò epingle", corridorFavoriteCountOne: "1 koridò favori", corridorFavoriteCountMany: "{count} koridò favori", providerFavoriteCountOne: "1 founisè favori", providerFavoriteCountMany: "{count} founisè favori", recentCountOne: "1 bagay resan", recentCountMany: "{count} bagay resan" },
  providerTrust: { ...en.providerTrust, heading: "Endikatè konfyans ak kalite founisè", intro: "Endikatè sa yo montre kijan plis enfòmasyon sou founisè ta ka parèt. Yo envante epi yo pa pwouve okenn verifikasyon, eksperyans, sèvis, asistans oswa estati regilasyon reyèl.", sampleLabel: "Done egzanp pou ilistrasyon", verified: "Verifikasyon pou egzanp", verifiedYes: "Nou montre li kòm verifye nan demonstrasyon sa a", verifiedNo: "Nou pa montre li kòm verifye nan demonstrasyon sa a", yearsInOperation: "Ane li ta nan aktivite", yearsValue: "{count} ane egzanp", countriesServed: "Peyi li ta sèvi", countriesValue: "{count} peyi egzanp", supportAvailability: "Lè asistans ta disponib", regulatoryStatus: "Estati regilasyon", lastProfileUpdate: "Dènye mizajou pwofil la", businessHours: "Lè travay pou egzanp", extendedHours: "Lè pwolonje pou egzanp", alwaysAvailable: "Disponiblite 24 sou 24 pou egzanp", demoRegistration: "Enskripsyon demonstrasyon parèt", demoPending: "Revizyon demonstrasyon an poko fini", notAssessed: "Nou pa evalye sa nan pwototip sa a" },
};
