export type Dictionary = {
  metadata: { homeTitle: string; homeDescription: string; marketplaceTitle: string; marketplaceDescription: string; waitlistTitle: string; waitlistDescription: string };
  common: { chooseLanguage: string; illustrativeUnavailable: string; fictionalProviders: string; sampleScenario: string; actualValuesMayDiffer: string; copyright: string };
  navigation: { primary: string; menu: string; home: string; marketplace: string; features: string; howItWorks: string; about: string; faq: string; waitlist: string; joinWaitlist: string; signIn: string; comingSoon: string; backHome: string };
  homepage: {
    hero: { eyebrow: string; titleStart: string; titleEmphasis: string; description: string; launchNote: string };
    features: { eyebrow: string; title: string; description: string; items: Array<{ id: string; title: string; description: string }> };
    howItWorks: { eyebrow: string; title: string; description: string; steps: Array<{ id: string; number: string; title: string; description: string }> };
    about: { eyebrow: string; titleStart: string; titleEnd: string; description: string; learnMore: string; items: Array<{ id: string; title: string; description: string }> };
    roadmap: { eyebrow: string; title: string; description: string; items: Array<{ id: string; number: string; title: string; timing: string; status: string }> };
    faq: { eyebrow: string; title: string; description: string; items: Array<{ id: string; question: string; answer: string }> };
    footer: { taglineStart: string; taglineEnd: string; navigationLabel: string; privacy: string; terms: string; security: string; contact: string; about: string; rights: string; disclosure: string };
  };
  comparison: {
    findOptions: string; compareTransfer: string; fromCountry: string; toCountry: string; amountToSend: string; amountHelp: string; quickAmounts: string; compareOptions: string; comparing: string; swapCountries: string; swapLabel: string; swapTitle: string; reverseUnavailable: string; preview: string; youSend: string; sampleBanner: string;
    payoutMethod: string; allPayoutMethods: string; bankDeposit: string; cashPickup: string; mobileWallet: string; cashOrBank: string; sortBy: string; bestValue: string; lowestFee: string; fastest: string; highestRecipient: string;
    provider: string; fee: string; rate: string; delivery: string; payout: string; recipientGets: string; actions: string; viewDetails: string; detailsOpen: string; noFilterResults: string; clearFilter: string; loading: string; unavailable: string; unavailableMessage: string;
    enterAmount: string; invalidAmount: string; minimumAmount: string; maximumAmount: string; notUpdated: string; comparingStatus: string; readyStatus: string; resultSingle: string; resultPlural: string; zeroResults: string; rangeFrom: string; detailsOpened: string; detailsClosed: string; filteredDetailsClosed: string;
    sortBestExplanation: string; sortFeeExplanation: string; sortFastestExplanation: string; sortRecipientExplanation: string;
  };
  providerDetails: { profile: string; overview: string; currentOffer: string; amountSent: string; exchangeRate: string; deliveryEstimate: string; recipientReceives: string; displayedIn: string; ofSendAmount: string; capabilities: string; payoutMethods: string; digitalAccess: string; supportChannels: string; availabilityNote: string; comparison: string; rankingNote: string; position: string; feePercentage: string; recipientDifference: string; deliveryPayout: string; importantNotice: string; close: string; sameAmount: string; lessAmount: string; moreAmount: string; positionOf: string; noBadge: string; notice: string };
  providerTrust: { heading: string; intro: string; sampleLabel: string; verified: string; verifiedYes: string; verifiedNo: string; yearsInOperation: string; yearsValue: string; countriesServed: string; countriesValue: string; supportAvailability: string; regulatoryStatus: string; lastProfileUpdate: string; businessHours: string; extendedHours: string; alwaysAvailable: string; demoRegistration: string; demoPending: string; notAssessed: string };
  marketplace: { eyebrow: string; title: string; intro: string; disclosure: string; footer: string; featured: string; recentlyAdded: string; browseAll: string; featuredDescription: string; recentDescription: string; browseDescription: string; search: string; searchPlaceholder: string; clearSearch: string; browseRegion: string; allRegions: string; resultSingle: string; resultPlural: string; empty: string; clearFilters: string; providerOffers: string; payoutMethods: string; compare: string };
  workspace: { title: string; disclosure: string; loading: string; empty: string; pinned: string; pinnedDescription: string; favorites: string; favoritesDescription: string; recents: string; recentsDescription: string; clearRecents: string; recentCleared: string; addFavorite: string; favorited: string; removeFavorite: string; pin: string; pinnedButton: string; unpin: string; favoriteFirst: string; loadingState: string; addedStatus: string; removedStatus: string; pinnedStatus: string; unpinnedStatus: string };
  workspaceCenter: { metadataTitle: string; metadataDescription: string; navLabel: string; eyebrow: string; title: string; intro: string; disclosure: string; localSummary: string; loading: string; empty: string; emptyDescription: string; pinned: string; favoriteCorridors: string; favoriteProviders: string; recentCorridors: string; recentProviders: string; clearRecentCorridors: string; clearRecentProviders: string; recentCorridorsCleared: string; recentProvidersCleared: string; removeFavorite: string; removeProviderFavorite: string; unpin: string; viewCorridors: string; exploreMarketplace: string; compareOptions: string; payoutCapabilities: string; digitalAccess: string; addProviderLabel: string; removeProviderLabel: string; addProviderText: string; providerFavoritedText: string; providerAddedStatus: string; providerRemovedStatus: string; corridorRemovedStatus: string; corridorUnpinnedStatus: string; pinnedCountOne: string; pinnedCountMany: string; corridorFavoriteCountOne: string; corridorFavoriteCountMany: string; providerFavoriteCountOne: string; providerFavoriteCountMany: string; recentCountOne: string; recentCountMany: string };
  waitlist: { nav: string; eyebrow: string; title: string; intro: string; localOnly: string; email: string; emailHint: string; firstName: string; optional: string; firstNamePlaceholder: string; country: string; selectCountry: string; other: string; consent: string; submit: string; submitting: string; noPayment: string; emailRequired: string; emailInvalid: string; consentRequired: string; storageError: string; newEyebrow: string; duplicateEyebrow: string; thanks: string; already: string; saved: string; registered: string; anotherEmail: string; successStatus: string; duplicateStatus: string; submittingStatus: string };
  countries: Record<"United States" | "Canada" | "France" | "Dominican Republic" | "Haiti", string>;
  regions: Record<"North America" | "Europe" | "Caribbean", string>;
  payoutMethods: Record<"Bank deposit" | "Cash pickup" | "Mobile wallet" | "Cash or bank", string>;
};
